import { Box, Button, ButtonGroup, Flex, Text, Heading, Fade } from "@chakra-ui/react";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import { onboarding } from "../data/onboard";
import { useRouter } from "next/router";

export default function Home() {
    const [slider, setSlider] = useState(0);
    const [isTransiting, setIsTransiting] = useState(false);

    const router = useRouter();

    const handleNext = (number = 1) => {
        setTimeout(() => {
            setIsTransiting(false);
            setSlider(slider + number);
        }, 200);
        setIsTransiting(true);
    };

    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Flex
                as="main"
                minH="100vh"
                minW="100vw"
                justify="center"
                alignItems="center"
                bg="primary.white"
            >
                <Flex
                    minH={{ base: "100vh", md: "600px" }}
                    w="100vw"
                    maxW={{ md: "500px" }}
                    maxH={{ md: "400px" }}
                    borderRadius={{ md: "12px" }}
                    bg="white"
                    px="24px"
                    justify="center"
                    alignItems="center"
                    flexDir="column"
                    py="32px"
                >
                    <Box w="200px" h="200px" borderRadius="12px" bg="primary.calmblue"></Box>

                    <Box
                        opacity={isTransiting ? "0.1" : "1"}
                        transition="ease-in"
                        transitionDuration="150ms"
                    >
                        <Heading
                            fontSize="h5"
                            fontWeight="normal"
                            letterSpacing="1.2px"
                            textAlign="center"
                            color="neutral.80"
                            mt="32px"
                        >
                            {onboarding[slider].title}
                        </Heading>

                        <Text fontSize="p2" color="neutral.80" mt="24px">
                            {onboarding[slider].desc}
                        </Text>
                    </Box>

                    <Flex alignItems="center" justify="center" gap="16px" mt="24px">
                        <Box
                            borderRadius="100px"
                            h="8px"
                            w="8px"
                            bg={slider == 0 ? "primary.calmblue" : "neutral.20"}
                        >
                            {" "}
                        </Box>
                        <Box
                            borderRadius="100px"
                            h="8px"
                            w="8px"
                            bg={slider == 1 ? "primary.calmblue" : "neutral.20"}
                        >
                            {" "}
                        </Box>
                        <Box
                            borderRadius="100px"
                            h="8px"
                            w="8px"
                            bg={slider == 2 ? "primary.calmblue" : "neutral.20"}
                        >
                            {" "}
                        </Box>
                    </Flex>

                    {slider == 2 ? (
                        <ButtonGroup variant="outline" spacing="16px" mt="60px" w="100%">
                            <Button variant="secondary" onClick={() => router.push("/register")}>
                                Registrasi
                            </Button>
                            <Button
                                variant="primary"
                                width="70%"
                                onClick={() => router.push("/login")}
                            >
                                Login
                            </Button>
                        </ButtonGroup>
                    ) : (
                        <ButtonGroup variant="outline" spacing="16px" mt="60px" w="100%">
                            <Button variant="secondary" onClick={() => handleNext(2)}>
                                Lewati
                            </Button>
                            <Button variant="primary" width="70%" onClick={() => handleNext(1)}>
                                Lanjutkan
                            </Button>
                        </ButtonGroup>
                    )}
                </Flex>
            </Flex>
        </div>
    );
}
